name: Brian Guay Art
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9283800476696342
title: "Look at Brian's Art Everyone!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e2b9'
    - '#aaa893'
    - '#000000'
    - '#322f27'
    - '#845340'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
