name: Brian Guay Art
favicon: null
layout_spectrum: 0.44352730456739664
typography_spectrum: 0.9283800476696342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7276763152331114
  lightness: 0.985628540860489
  saturation: 0.04095213976688683
  rhythmicContrast: 0.40730344550684094
purpose: []
